import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "remixicon/fonts/remixicon.css";
import ScrollToTop from "@/components/ScrollToTop";

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Company Name",
  description: "Generated by Afrizal",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.className} antialiased`} id="home"
      >
        <ScrollToTop />
        <Navbar />
        <div className="container mx-auto px-4 sm:px-6 lg:px-8" >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
